### ISSUE TITLE
Character Favourites 

### ISSUE THREAD

**Issue by Reh347** [croberts22/myanilist-bugs#18]
When you favourite characters after a certain number when I favourite more they just disappear after a while. Random characters end up being favourites so the problem is after a certain amount it doesn’t let me keep favourites on my list .

**Comment by croberts22** [comment]
Hey @Reh347! This sounds like an issue I've been aware of some time, and I intend to get that fixed in an upcoming version. There's currently a limitation of showing 25 favorites on your profile in the app, but the website likely shows more than that. If that isn't the issue you're seeing though, would you mind further elaborating on how you can reproduce the issue? Thanks!

**Comment by Reh347** [comment]
Ah thank you since I use the app I wasn’t aware of the 25 limit rule.  I just checked however and I’ve favourited 24 characters but for some reason it randomly favourites a 25th character from either a manga/WEBTOON or anime that I’ve watched without me having favourited them.

**Comment by croberts22** [comment]
This will be fixed in version 2.10.2! 🎉

**Comment by croberts22** [comment]
Published in 2.10.2! 🎉
