### ISSUE TITLE
iOS App crashes when searching for anime containing word "Rikei"

### ISSUE THREAD

**Issue by habaieba** [croberts22/myanilist-bugs#20]
## Describe the issue

Should list all anime containing "Rikei" in their name.

## How reproducible is this issue?

Every time

## Device Information

iOS Version: 15.11

MyAniList Version: 2.10.1 Mona v2

iOS Device: iPhone 13

Jailbroken: No

**Comment by croberts22** [comment]
This is an interesting bug. It looks like there's a slight bug in AniList's database where there are three instances of a user with the same username (`hikarikeiever25`). Given the rules of usernames on AniList, it's possible having duplicated usernames may have been possible long ago. The IDs for each account is unique, but it seems like uniqueness in usernames in this situation is not honored. 

This will be fixed in 2.10.2 👍

**Comment by croberts22** [comment]
Published in 2.10.2! 🎉
