### ISSUE TITLE
Anime loading bar doesn't increment uniformly

### ISSUE THREAD

**Issue by seanblue** [croberts22/myanilist-bugs#31]
In the 2.10.2 beta, the loading bar when pulling down my anime list barely moves several times and then suddenly jumps all the way to the end. Previously it incremented more uniformly.

Additionally, the first time this happened the app froze for several seconds after the list supposedly finished updating. I have no idea if this was related or even caused by the app. 

Let me know if you need a video of this issue. If so I'll email it.

**Comment by croberts22** [comment]
Looks like Josh at AniList mentioned they have changed some of the properties of paging logic temporarily due to server load concerns: https://discord.com/channels/353213344418889730/353213955080060948/931415439928614934

MyAniList utilizes the `totalCount` value here as a projected value for how many shows need to be downloaded. Since this value is now not entirely accurate, the progress bar will unfortunately assume that you have 5000 series to synchronize on your list. I'm hoping this is just temporary. 

I might have to remove the progress bar entirely, or try to "fake" the progress by assuming the number of items on your list currently.

**Comment by seanblue** [comment]
That's annoying. I think using the current list count should be very close to the real total the vast majority of the time. So that's not a bad idea as a workaround. 

Do you have any way of knowing when AniList returns the real total versus a fake total? That would be ideal so that you can use the real numbers from the API when provided, but otherwise fall back to the current list size.

**Comment by croberts22** [comment]
Published in 2.10.2! 🎉
