### ISSUE TITLE
Recommendation is missing

### ISSUE THREAD

**Issue by seanblue** [croberts22/myanilist-bugs#42]
On the page for Baccano, the recommendation for Odd Taxi is missing.

Compare the website:
![image](https://user-images.githubusercontent.com/5884067/152630030-c4ad93e1-d495-4842-8298-bcc873aac8b2.jpeg)

To the app:
![image](https://user-images.githubusercontent.com/5884067/152630038-a130bf2c-df01-4e05-b2ad-a170d4fdb1c9.jpeg)

I'm currently watching Odd Taxi, in case that happens to be relevant. If I go to the Odd Taxi page in the app, Baccano does appear as expected.

**Comment by croberts22** [comment]
Ah, I just saw the problem here. Apparently I forgot that recommendations here can be pageable, so it's only sending back the first 25 recommendations based on some unique sort order. Given I have some work I'd like to do here to make paging items on this page more optimal, I think what I'll do is adjust the query to return items sorted based on user ratings for now. I'll file a separate bug to adjust this list (and additional lists) to dynamically fetch next pages as you scroll towards the end.

I had no idea a series could have so many recommendations! 😄

**Comment by croberts22** [comment]
This has been published in 2.11.1 and will be available in the next beta 🥳
