### ISSUE TITLE
Adaption of anime not showing the manga page

### ISSUE THREAD

**Issue by Weird-Davey** [croberts22/myanilist-bugs#6]
![image](https://user-images.githubusercontent.com/94107417/142268250-e6e298c2-6196-4983-bc5c-39f099673480.png)

![image](https://user-images.githubusercontent.com/94107417/142268306-e2fac1a7-e577-46a1-91fb-9757910895ba.png)

![image](https://user-images.githubusercontent.com/94107417/142268354-e285de48-1afc-43e9-9a2e-ce1f6ce73b7c.png)

So the first 2 images it doesn't show there's a anime of that manga/LN it only shows each other (that being the manga/ LN) but when I search the name it'll bring up the anime, ova, and unaired eps too and if I click on the anime it'll show that it's related to the manga/LN but if I try to find the anime from the manga page it won't show it.

**Comment by croberts22** [comment]
This is because the relations are represented that way on AniList.co:

[Sankarea](https://anilist.co/manga/48597/Sankarea/)

![image](https://user-images.githubusercontent.com/744905/145157187-bbdeec17-1748-4aeb-bb3e-d73d70510e3d.png)

[Sankarea: All Night Rea Long](https://anilist.co/manga/85757/Sankarea-All-Night-Rea-Long/)

![image](https://user-images.githubusercontent.com/744905/145157204-c3a5885d-093e-4eca-b941-445a0e102848.png)

For most manga/source material on AniList.co, adaptations usually only show the primary anime that adapted it and not so much any other miscellaneous content (like OVAs, sequels, etc).
