### ISSUE TITLE
Bug with search

### ISSUE THREAD

**Issue by edward070707** [croberts22/myanilist-bugs#80]
When I try to search an anime o manga, the app don’t search me nothin and the screen page is always of loading page

**Comment by croberts22** [comment]
Recently, AniList.co has been undergoing website maintenance that has imposed some limitations on how third-party apps like MyAniList operate. Specifically, visiting a page like the Discover page (which downloads a handful of trending and ranked lists) can hit a particular limit on network requests that prevent MyAniList from finishing displaying these lists to you. Starting with version 3.0.5 (coming soon), when this happens, you will see messages that appear near the top of the app mentioning that there may be active maintenance going on. Normally this limit is much higher, but due to active maintenance and mitigating server overload, they have lowered this limit to reduce churn on their servers. This unfortunately causes MyAniList to appear slow and prevents the app from downloading content temporarily. I apologize for the inconvenience! This is something unfortunately out of my control.

As a reminder, I do not own AniList.co and I unfortunately do not have any timeline as to when maintenance updates begin or end. If the app appears slow to update, please check AniList.co's Twitter or Discord for any updates on when maintenance will finish. I will also keep updating here on any updates that I get. 

More info here: https://discord.com/channels/210521487378087947/457951807046549525/1040687539691995206

Thanks and apologies for the inconvenience.
